// Code generated by Kitex v0.6.2. DO NOT EDIT.

package loginservice

import (
	"context"
	login "github.com/Tiktok-Lite/kotkit/kitex_gen/login"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Register(ctx context.Context, Req *login.UserRegisterRequest, callOptions ...callopt.Option) (r *login.UserRegisterResponse, err error)
	Login(ctx context.Context, Req *login.UserLoginRequest, callOptions ...callopt.Option) (r *login.UserLoginResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kLoginServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kLoginServiceClient struct {
	*kClient
}

func (p *kLoginServiceClient) Register(ctx context.Context, Req *login.UserRegisterRequest, callOptions ...callopt.Option) (r *login.UserRegisterResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, Req)
}

func (p *kLoginServiceClient) Login(ctx context.Context, Req *login.UserLoginRequest, callOptions ...callopt.Option) (r *login.UserLoginResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, Req)
}
